"""컷씬 대본 v5(markdown) → Assets/_CoastRun/Scripts/Story/ChapterScript.Data.cs
사용: python build_chapter_script.py [대본.md]
【착각】/【진실】/제작 메모는 제외한다(플레이어에게 안 보임)."""
import re, sys, os, io
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "..", "..", "..", "Users", "ares2", "OneDrive", "Desktop", "송전탑", "컷씬_대본_v5_엇갈림.md")
OUT = os.path.join(HERE, "..", "..", "Assets", "_CoastRun", "Scripts", "Story", "ChapterScript.Data.cs")

def esc(s): return s.replace("`", "").replace("\\", "\\\\").replace('"', '\\"')

scenes = {}   # id -> list of tuples
titles = {}
order = []
cur = None; part = None; chapter = 0

def open_scene(sid):
    global cur
    cur = sid
    if sid not in scenes:
        scenes[sid] = []; order.append(sid)

text = io.open(SRC, encoding="utf-8").read().splitlines()
for raw in text:
    line = raw.strip()
    if not line: continue
    m = re.match(r"^### CH(\d+) 「(.+?)」", line)
    if m:
        chapter = int(m.group(1)); titles[chapter] = m.group(2)
        open_scene(f"CH{chapter:02d}_Open"); part = "open"; continue
    if line.startswith("## 프롤로그"):
        chapter = 0; open_scene("PRO"); part = "open"; continue
    if line.startswith("## 엔딩 A"):
        chapter = 0; open_scene("END_A"); part = "open"; continue
    if line.startswith("## 엔딩 B"):
        chapter = 0; open_scene("END_B"); part = "open"; continue
    if line.startswith("## 부록"):
        cur = None; continue
    if cur is None: continue
    if line.startswith("**런**"):
        if chapter: open_scene(f"CH{chapter:02d}_Close")
        continue
    if line.startswith("**클로징**") or line.startswith("(클로징 없음"):
        continue
    if line.startswith("---") or line.startswith("## "):
        continue
    if line.startswith("【") or line.startswith("→"):
        continue
    m = re.match(r"^`\[BG ([^\s\]|]+)(?:\(([^)]*)\))?\s*(?:\|\s*(.*?))?\]`", line)
    if m:
        bg = m.group(1); variant = m.group(2) or ""; rest = m.group(3) or ""
        L = R = ""
        for tok in re.findall(r"([LR]):([^\s(]+)\(([^)]+)\)", rest):
            who = f"{tok[1]}:{tok[2]}"
            if tok[0] == "L": L = who
            else: R = who
        scenes[cur].append(("BG", bg, L, R, variant)); continue
    m = re.match(r"^`\[CG ([^\s\]—]+)\s*—?\s*(.*?)\]`", line)
    if m:
        scenes[cur].append(("CG", m.group(1), m.group(2), "", "")); continue
    m = re.match(r"^\(지문\)\s*(.*)$", line)
    if m:
        scenes[cur].append(("NARR", "", m.group(1), "", "")); continue
    m = re.match(r"^(\S+) 「(.*)」$", line)
    if m and not line.startswith("("):
        scenes[cur].append(("SAY", m.group(1), m.group(2), "", "")); continue
    m = re.match(r"^「(.*)」$", line)
    if m:
        scenes[cur].append(("LETTER", "", m.group(1), "", "")); continue
    if line.startswith("("):
        continue  # 지문이 아닌 괄호 메모

out = io.StringIO()
out.write("// <auto-generated> Tools/Story/build_chapter_script.py — 컷씬_대본_v5_엇갈림.md 에서 생성. 직접 편집하지 말 것.\n")
out.write("using System.Collections.Generic;\n\nnamespace CoastRun\n{\n    public static partial class ChapterScript\n    {\n")
out.write("        public static readonly Dictionary<int, string> Titles = new Dictionary<int, string>\n        {\n")
for k in sorted(titles): out.write(f'            {{ {k}, "{esc(titles[k])}" }},\n')
out.write("        };\n\n        public static readonly Dictionary<string, VnLine[]> Scenes = new Dictionary<string, VnLine[]>\n        {\n")
for sid in order:
    lines = scenes[sid]
    if not lines: continue
    out.write(f'            {{ "{sid}", new[]\n            {{\n')
    for kind, a, b, c, d in lines:
        out.write(f'                new VnLine("{kind}", "{esc(a)}", "{esc(b)}", "{esc(c)}", "{esc(d)}"),\n')
    out.write("            } },\n")
out.write("        };\n    }\n}\n")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
io.open(OUT, "w", encoding="utf-8", newline="\n").write(out.getvalue())
print("scenes:", len([s for s in order if scenes[s]]), "lines:", sum(len(v) for v in scenes.values()))
for sid in order: print(f"  {sid}: {len(scenes[sid])}")
