using System.Collections.Generic;

namespace CoastRun
{
    /// 컷씬 대사 영어판 — key "<sceneId>:<line index>" (Tools/Story/cutscene_txt.py import 로 생성). 영어 모드(Loc.IsKo == false)에서 ChapterVN이 사용.
    public static partial class ChapterScript
    {
        public static string SpeakerEn(string ko)
        {
            switch (ko)
            {
                case "하늘": return "Haneul";
                case "도윤": return "Doyun";
                case "루아": return "Rua";
                case "만수": return "Mansu";
                case "할머니": return "Grandma";
                case "라디오": return "Radio";
                case "DJ": return "DJ";
                case "아빠": return "Dad";
                case "엄마": return "Mom";
                case "바다": return "Bada";
                case "꼬마": return "Kid";
                case "아이들": return "Kids";
                case "큰 아저씨": return "Big Suit";
                case "마른 아저씨": return "Thin Suit";
                case "기사": return "Driver";
                default: return ko;
            }
        }

        /// 영어 텍스트. 없으면 null(한국어 유지).
        public static string TextEn(string sceneId, int index)
        {
            return En.TryGetValue(sceneId + ":" + index, out var s) ? s : null;
        }

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            // PRO
            { "PRO:1", "A classroom. Alone by the window. The seat beside her is empty. The kids hold their noses." },
            { "PRO:2", "Don't sit there." },
            { "PRO:3", "It stinks." },
            { "PRO:4", "Lunch. The steps behind the field. No lunchbox. She hugs her knees." },
            { "PRO:6", "Backlight in the classroom door. A pale boy. Two black suits stuck in the doorframe behind him." },
            { "PRO:7", "Where do I sit?" },
            { "PRO:8", "He drops his bag on that empty seat. The kids snicker." },
            { "PRO:9", "My nose doesn't work well." },
            { "PRO:10", "Same angle. Five days. A hand held out across the desk." },
            { "PRO:11", "Hand." },
            { "PRO:12", "Why." },
            { "PRO:13", "Hand." },
            { "PRO:14", "Don't make fun of me." },
            { "PRO:15", "Hand." },
            { "PRO:16", "(She ignores him.)" },
            { "PRO:17", "Hand." },
            { "PRO:18", "What happened to your hand." },
            { "PRO:19", "I fell." },
            { "PRO:20", "Hand." },
            { "PRO:21", "Day five. A candy on his palm. For the first time, she looks at the hand." },
            { "PRO:22", "I'm not teasing. You're my seatmate." },
            { "PRO:24", "The hill out back. The girl, shoved to the ground. An empty lunchbox rolls out." },
            { "PRO:25", "Hey. It's empty." },
            { "PRO:26", "It's always empty." },
            { "PRO:28", "Young master! Don't run!" },
            { "PRO:29", "The boy runs up out of breath and stands in front of her. We only see his back. His shoulders heave." },
            { "PRO:30", "Stop it." },
            { "PRO:31", "Two black suits step out of the tree shade. The kids scatter. The boy braces on his knees." },
            { "PRO:32", "I'm fine. I'm fine." },
            { "PRO:33", "Two hands, held. A single fish scale on the back of her hand." },
            { "PRO:34", "What's with your hand." },
            { "PRO:35", "It's always like this." },
            { "PRO:36", "It's cold." },
            { "PRO:37", "It's always like this." },
            { "PRO:39", "Two lunchboxes. A face crying over sea urchin. Two faces breathed onto a winter window. The coast road: a girl on a board, a boy walking, two suits running behind." },
            { "PRO:40", "A black sedan pulls away. The girl jumps on her board and chases. A palm pressed to the rear window. Only the lips move." },
            { "PRO:41", "(mouthing) Twenty. Your birthday. Under the tower." },
            { "PRO:42", "The board catches a stone. She falls. The car turns the corner." },
            { "PRO:45", "White. The sound of water, once." },
            { "PRO:48", "A ceiling. Nineteen, opening her eyes. Blank. By the door, a kid in an orange raincoat, crouched." },
            { "PRO:49", "You're up." },
            { "PRO:50", "The calendar: 'My birthday — under the tower — Doyun.' The bus stop: 'Out of service.'" },
            { "PRO:51", "Who's Doyun." },
            { "PRO:52", "Dunno." },
            { "PRO:53", "A heart on the coast road. She rubs her eyes. It stays. The kid points at the tower." },
            { "PRO:54", "4.2 kilometers." },
            { "PRO:56", "— Our Frequency —" },
            // CH01_Open
            { "CH01_Open:1", "She wakes. There's a kid by the door." },
            { "CH01_Open:2", "Who are you." },
            { "CH01_Open:3", "Dunno." },
            { "CH01_Open:4", "Why are you here." },
            { "CH01_Open:5", "Dunno." },
            { "CH01_Open:6", "The mirror stays fogged no matter how she wipes it. Villagers brush past her shoulder and never turn. But this kid sees her." },
            { "CH01_Open:7", "You're always staring at the sea. So — Bada." },
            { "CH01_Open:8", "Why 'Bada'?" },
            { "CH01_Open:9", "Just because." },
            { "CH01_Open:10", "One line on the calendar. The bus stop: 'Out of service.' The kid leans the board by the door and points at the tower." },
            { "CH01_Open:11", "The tower." },
            { "CH01_Open:12", "[게이트>=0]…I think I can run today." },
            { "CH01_Open:13", "[게이트<0]…My legs aren't ready. One more week." },
            // CH01_Close
            { "CH01_Close:1", "On the stone under the tower, two cartons of milk. Only one is open. Still cold." },
            { "CH01_Close:2", "The kid is already sitting under the tower. They left the house together." },
            { "CH01_Close:3", "You're late." },
            { "CH01_Close:4", "How did you get here." },
            { "CH01_Close:5", "Dunno." },
            { "CH01_Close:6", "She touches the tower at night. Cold steel. Nothing comes." },
            // CH02_Open
            { "CH02_Open:1", "Two diving suits on the back clothesline. Twenty letters in the mailbox, same handwriting, all unopened." },
            { "CH02_Open:2", "Holding one in the yard, the wind snatches it. It flies toward the coast road. She runs after it." },
            { "CH02_Open:3", "The letter catches in the silvergrass under the tower. Reaching for it, her hand touches the tower's leg — with half the sunset left." },
            { "CH02_Open:5", "You don't hold your breath. You save it." },
            { "CH02_Open:7", "The first piece comes. Mom's sumbi breath. She lets go. Touches again. Nothing." },
            { "CH02_Open:8", "[게이트>=0]…I think I can run today." },
            { "CH02_Open:9", "[게이트<0]…My legs aren't ready. One more week." },
            // CH02_Close
            { "CH02_Close:1", "White chrysanthemums on the empty market stall. Yesterday, today — fresh every day." },
            { "CH02_Close:2", "These are for you." },
            { "CH02_Close:3", "The letter goes into her pocket, still unopened." },
            // CH03_Open
            { "CH03_Open:1", "She touches the 'Doyun' on the calendar. The ink doesn't run." },
            { "CH03_Open:2", "For the first time she runs on purpose. To make it before sunset. From here on, every day." },
            { "CH03_Open:3", "One more, then we go." },
            { "CH03_Open:4", "[게이트>=0]…I think I can run today." },
            { "CH03_Open:5", "[게이트<0]…My legs aren't ready. One more week." },
            // CH03_Close
            { "CH03_Close:1", "A thin back disappearing into the silvergrass. She calls; the steps pause once, then go on." },
            { "CH03_Close:2", "One calendar line copied for eight years. The candy on day five." },
            // CH04_Open
            { "CH04_Open:1", "Sunset. A hand touches the tower's leg. A hum. The picture turns sepia." },
            { "CH04_Open:4", "The harbor. Dad paints a heart on a white buoy. Seven-year-old Haneul watches. The same heart on the bow." },
            { "CH04_Open:5", "Haneul. Look at this." },
            { "CH04_Open:6", "If you see this from the cliff, that's Dad's boat." },
            { "CH04_Open:7", "Why a heart?" },
            { "CH04_Open:8", "It's the only thing Dad knows how to draw." },
            { "CH04_Open:9", "A stone wall. Dad stacks three small stones. Haneul copies him and knocks them over. Dad stacks them again." },
            { "CH04_Open:10", "As long as they stand, I'm still out at sea." },
            { "CH04_Open:11", "The evening before the typhoon. The kitchen. He pulls on a raincoat. Mom grabs his sleeve." },
            { "CH04_Open:12", "A typhoon's coming. Where are you going." },
            { "CH04_Open:13", "Just to the tower." },
            { "CH04_Open:14", "It's her birthday tomorrow and I've got nothing to give her." },
            { "CH04_Open:15", "Just one more catch and we're fine." },
            { "CH04_Open:16", "Please. Just stop." },
            { "CH04_Open:17", "Dad lifts her hand away and sets it on his daughter's head." },
            { "CH04_Open:18", "Go to sleep." },
            { "CH04_Open:20", "The door closes. The radio on the shelf crackles. Rain outside." },
            { "CH04_Open:21", "Haneul. Tomorrow." },
            { "CH04_Open:22", "(It cuts out.)" },
            { "CH04_Open:24", "On the cliff. Seven, in a yellow raincoat. Black waves. Far out, one red heart rises." },
            { "CH04_Open:25", "She waves both arms. The heart slips behind a wave. She keeps waving. It doesn't come back. She doesn't lower her arms." },
            { "CH04_Open:28", "Next morning. Cruelly clear. One candle in a rice bowl. Mom, hair wet. Haneul doesn't blow. Mom blows it out for her." },
            { "CH04_Open:29", "Happy birthday." },
            { "CH04_Open:30", "Outside the window, the stone wall. Three stones, still standing." },
            { "CH04_Open:33", "She opens her eyes. Evening under the tower. The kid in the orange raincoat sits beside her, looking at her cheek." },
            { "CH04_Open:34", "Were you crying?" },
            { "CH04_Open:35", "No." },
            { "CH04_Open:36", "The kid takes a heart-shaped stone from his pocket and presses it into her hand." },
            { "CH04_Open:37", "Found one more." },
            { "CH04_Open:38", "Let's go home." },
            { "CH04_Open:39", "[게이트>=0]…I think I can run today." },
            { "CH04_Open:40", "[게이트<0]…My legs aren't ready. One more week." },
            // CH04_Close
            { "CH04_Close:1", "The heart from the end of the opening — Dad's hand painted it." },
            // CH05_Open
            { "CH05_Open:1", "The lunchbox smells of egg roll. Ten hearts. She smiles for the first time." },
            { "CH05_Open:2", "She tries to follow the coast road to the end. It doesn't continue." },
            { "CH05_Open:3", "Inside the lunchbox lid, twelve-year-old handwriting: 'Half is yours.'" },
            { "CH05_Open:4", "[게이트>=0]…I think I can run today." },
            { "CH05_Open:5", "[게이트<0]…My legs aren't ready. One more week." },
            // CH05_Close
            { "CH05_Close:1", "They pass on the tower steps. The hand that reaches for his shoulder goes through." },
            { "CH05_Close:2", "Three stones stacked on the wall. The kid dusts off his hands." },
            { "CH05_Close:3", "Why stack them?" },
            { "CH05_Close:4", "Dunno. Just because." },
            // CH06_Open
            { "CH06_Open:1", "First snow. On the frosted window she draws two smiling faces without thinking, then stops." },
            { "CH06_Open:2", "She slips on the ice toward the cliff. The kid grabs her arm." },
            { "CH06_Open:3", "You're strong." },
            { "CH06_Open:4", "Not there." },
            { "CH06_Open:5", "Why." },
            { "CH06_Open:6", "Just because." },
            { "CH06_Open:7", "[게이트>=0]…I think I can run today." },
            { "CH06_Open:8", "[게이트<0]…My legs aren't ready. One more week." },
            // CH06_Close
            { "CH06_Close:1", "Under the snowy tower, only one line of footprints. The kid's prints stay; Haneul's are shallow." },
            { "CH06_Close:2", "Two faces on a winter classroom window." },
            // CH07_Open
            { "CH07_Open:1", "Snow under the tower. Only one line of footprints. Haneul looks beside her own feet. Hand on the tower." },
            { "CH07_Open:4", "Classroom. Two lunchboxes: one shiny, one dented. Two pairs of chopsticks reach for the same egg roll." },
            { "CH07_Open:5", "Half is true. I can't eat much." },
            { "CH07_Open:6", "Liar." },
            { "CH07_Open:7", "Half a lie." },
            { "CH07_Open:8", "Behind a market stall. Sea urchin in newspaper. The boy chews, then stops. His eyes well up." },
            { "CH07_Open:9", "It tastes like the sea." },
            { "CH07_Open:10", "It's just salty." },
            { "CH07_Open:11", "First time I've eaten the sea." },
            { "CH07_Open:12", "Are you crying?" },
            { "CH07_Open:13", "It's salty." },
            { "CH07_Open:14", "A winter window. Two faces drawn in breath. One fades first." },
            { "CH07_Open:15", "If it fades, we draw it again." },
            { "CH07_Open:16", "The coast road. A new board. She rides. He walks. Two suits run behind. She looks back and laughs." },
            { "CH07_Open:17", "I can't ride. If you ride, I get to watch." },
            { "CH07_Open:18", "Young master! Slow down!" },
            { "CH07_Open:19", "I'm not running!" },
            { "CH07_Open:20", "Chalk on the asphalt: 4.2. From the bus stop to the tower." },
            { "CH07_Open:21", "Reach it before sunset and you win." },
            { "CH07_Open:22", "And how do you win." },
            { "CH07_Open:23", "I wait. Under the tower." },
            { "CH07_Open:24", "What's hard about that." },
            { "CH07_Open:26", "Waiting is the hardest thing." },
            { "CH07_Open:28", "Under the sunset. She puts her ear to his chest. Only a heartbeat." },
            { "CH07_Open:29", "It's broken, that's why." },
            { "CH07_Open:30", "It's not broken." },
            { "CH07_Open:31", "Then what." },
            { "CH07_Open:32", "It's fast." },
            { "CH07_Open:33", "Only the sunset." },
            { "CH07_Open:35", "She opens her eyes. A winter window. She draws one face in her breath. Reaches to draw the second and her hand stops." },
            { "CH07_Open:36", "Beyond the glass, a thin back passes on the road. She knocks. Twice. Three times. He doesn't turn." },
            { "CH07_Open:37", "The one face on the glass fades." },
            { "CH07_Open:38", "[게이트>=0]…I think I can run today." },
            { "CH07_Open:39", "[게이트<0]…My legs aren't ready. One more week." },
            // CH07_Close
            { "CH07_Close:1", "She knocks as he passes beyond the glass. He doesn't turn." },
            // CH08_Open
            { "CH08_Open:1", "She climbs below the cliff for the first time. A heart buoy in the rocks. The red paint is fresh; it comes off on her hand." },
            { "CH08_Open:2", "Today there isn't a single heart on the road. A first." },
            { "CH08_Open:3", "Pretty, right?" },
            { "CH08_Open:4", "[게이트>=0]…I think I can run today." },
            { "CH08_Open:5", "[게이트<0]…My legs aren't ready. One more week." },
            // CH08_Close
            { "CH08_Close:1", "Twelve years ago: Dad's hand holding the brush." },
            // CH09_Open
            { "CH09_Open:1", "At 3 km her steps slow, then stop." },
            { "CH09_Open:2", "One more." },
            { "CH09_Open:3", "Not today." },
            { "CH09_Open:4", "She turns and walks back down. The sun sets. That night her finger runs down the calendar and stops on Dad's anniversary. The next square is her birthday." },
            { "CH09_Open:5", "Day two. A candle is burning on the stone. As she approaches, it goes out." },
            { "CH09_Open:6", "[게이트>=0]…I think I can run today." },
            { "CH09_Open:7", "[게이트<0]…My legs aren't ready. One more week." },
            // CH09_Close
            { "CH09_Close:1", "'One more' — the first day it doesn't work. Why she hated that spot even as she went every day." },
            // CH10_Open
            { "CH10_Open:1", "Under the tower. An eight-year-old candle stub on the stone. A hand." },
            { "CH10_Open:4", "Twelve candles under the tower. Two suits in party hats hold a cake awkwardly. The boy claps." },
            { "CH10_Open:5", "Happy birthday." },
            { "CH10_Open:6", "The guys found out your birthday." },
            { "CH10_Open:7", "This is your favorite place, right? You come every day." },
            { "CH10_Open:8", "She doesn't move. Her face wavers in the candlelight." },
            { "CH10_Open:9", "What. What's wrong." },
            { "CH10_Open:10", "Put them out." },
            { "CH10_Open:11", "Huh?" },
            { "CH10_Open:12", "I said put them out." },
            { "CH10_Open:14", "She kicks the candles. The cake lands in the grass. The big man reaches to pick it up, then doesn't." },
            { "CH10_Open:15", "Do you know what this place is?" },
            { "CH10_Open:16", "What would someone like you know." },
            { "CH10_Open:17", "She runs the 4.2 km back down. The boy runs after her. Three steps. The big man catches his arm." },
            { "CH10_Open:18", "Young master. You can't." },
            { "CH10_Open:19", "Let go." },
            { "CH10_Open:20", "Young master." },
            { "CH10_Open:21", "(His arm goes slack.)" },
            { "CH10_Open:23", "Night. Still in his party hat, he sits before the dead candles. The thin man holds an umbrella over him." },
            { "CH10_Open:24", "What did I do wrong?" },
            { "CH10_Open:25", "I don't know." },
            { "CH10_Open:26", "If you don't know, who does." },
            { "CH10_Open:29", "Ten days. Day 1: one lunchbox on the desk, untouched. Day 3: the seat beside him empty, his profile pale. Day 5: her lunchbox goes under the desk." },
            { "CH10_Open:30", "Day 8: he leaves the lunchbox and walks out. His back. Day 9: the board sits on the wall of Haneul's yard. She sees it. Doesn't take it." },
            { "CH10_Open:32", "Day 10. In front of the store. Mansu looks at the boy." },
            { "CH10_Open:33", "That's where that girl's father died." },
            { "CH10_Open:34", "What?" },
            { "CH10_Open:35", "Under the tower. In the typhoon. The day before her birthday." },
            { "CH10_Open:37", "I didn't know." },
            { "CH10_Open:38", "A raindrop on the boy's cheek. He looks up. He starts to run." },
            { "CH10_Open:40", "Rain. The empty spot under the tower. The kid stands beside her." },
            { "CH10_Open:41", "Not here today either." },
            { "CH10_Open:42", "[게이트>=0]…I think I can run today." },
            { "CH10_Open:43", "[게이트<0]…My legs aren't ready. One more week." },
            // CH10_Close
            { "CH10_Close:1", "The rain begins." },
            // CH11_Open
            { "CH11_Open:1", "An overturned handcart buried in the yard grass. The lone house, 2 km from the village." },
            { "CH11_Open:2", "He's back. In the rain, no umbrella, standing under the tower. When she runs to him, he's gone. Ten days." },
            { "CH11_Open:3", "A truck comes through the rain without slowing. The kid yanks her aside. The truck passes right through where she stood." },
            { "CH11_Open:4", "Did he not see me?" },
            { "CH11_Open:5", "Let's go." },
            { "CH11_Open:6", "[게이트>=0]…I think I can run today." },
            { "CH11_Open:7", "[게이트<0]…My legs aren't ready. One more week." },
            // CH11_Close
            { "CH11_Close:1", "From this day the kid's raincoat sleeve is torn. Why the handcart is in the yard." },
            // CH12_Open
            { "CH12_Open:1", "She rights the handcart. The paint is worn off the handle in two places. Her hand fits one. The wheel is jammed." },
            { "CH12_Open:2", "Mister. The wheel." },
            { "CH12_Open:3", "He doesn't turn. The bell rings once and the door closes." },
            { "CH12_Open:4", "Back from the run, the cart has been moved to the roadside. The wheel is new. It turns." },
            { "CH12_Open:5", "Who did this." },
            { "CH12_Open:6", "Came at night." },
            { "CH12_Open:7", "Who." },
            { "CH12_Open:8", "A tall person." },
            { "CH12_Open:9", "[게이트>=0]…I think I can run today." },
            { "CH12_Open:10", "[게이트<0]…My legs aren't ready. One more week." },
            // CH12_Close
            { "CH12_Close:1", "Two worn spots on the handle — two twelve-year-old hands. The only things that change in this village are the ones he touches." },
            // CH13_Open
            { "CH13_Open:1", "Rain. Haneul, soaked, hand on the tower. Beside her the kid stays dry in his raincoat." },
            { "CH13_Open:2", "Guess you're not cold." },
            { "CH13_Open:5", "A downpour. The door of the lone house. The boy stands drenched. Inside, she holds the latch and won't open." },
            { "CH13_Open:6", "I didn't know." },
            { "CH13_Open:7", "Go." },
            { "CH13_Open:8", "I didn't know, and I'm still sorry." },
            { "CH13_Open:9", "I said go." },
            { "CH13_Open:11", "He turns away. The yard. Her mother, face-down in the grass. He sees her first. He pounds on the door." },
            { "CH13_Open:12", "Haneul." },
            { "CH13_Open:13", "Open the door." },
            { "CH13_Open:14", "Your mom." },
            { "CH13_Open:15", "The door opens. She runs out barefoot." },
            { "CH13_Open:16", "Mom. Mom." },
            { "CH13_Open:17", "The phone. No signal. Lightning. The tower on the hill flashes. She looks down the road: 2 km." },
            { "CH13_Open:18", "Hospital." },
            { "CH13_Open:19", "Two kilometers." },
            { "CH13_Open:20", "The cart." },
            { "CH13_Open:22", "A mud road. The handcart. The wheel sinks. Two twelve-year-old shoulders. The boy's lips are blue." },
            { "CH13_Open:23", "You take the front. I'll push." },
            { "CH13_Open:24", "Your breathing." },
            { "CH13_Open:25", "Go." },
            { "CH13_Open:26", "Your breathing sounds wrong." },
            { "CH13_Open:27", "I said go." },
            { "CH13_Open:29", "Headlights. The black sedan. Both doors open at once. The boy drops to his knees in the mud. The big man drops his umbrella." },
            { "CH13_Open:30", "Young master!" },
            { "CH13_Open:32", "Please." },
            { "CH13_Open:33", "Save her." },
            { "CH13_Open:34", "Her mom." },
            { "CH13_Open:35", "Please." },
            { "CH13_Open:36", "The thin man lifts her mother. He runs, for the first time. The back seat. No room." },
            { "CH13_Open:37", "You get in too." },
            { "CH13_Open:38", "There's no room." },
            { "CH13_Open:39", "Young master." },
            { "CH13_Open:40", "Go." },
            { "CH13_Open:42", "The car leaves. The boy lies down in the mud. She puts her ear to his chest. Slow. She takes his hand. Rain on both faces." },
            { "CH13_Open:43", "Hey." },
            { "CH13_Open:44", "Han Doyun." },
            { "CH13_Open:45", "Were you scared?" },
            { "CH13_Open:46", "Yeah." },
            { "CH13_Open:47", "Me too." },
            { "CH13_Open:49", "A hospital room. Two beds. She wakes." },
            { "CH13_Open:50", "His mom— my mom. Is she okay." },
            { "CH13_Open:51", "She's fine." },
            { "CH13_Open:52", "What time is sunset today." },
            { "CH13_Open:53", "Through the door crack. The hallway. The big man's back. She listens from under the blanket." },
            { "CH13_Open:54", "Stay here and you'll die. Go to Seoul." },
            { "CH13_Open:57", "She opens her eyes. Three wet stones. A hand with a torn sleeve reaches in." },
            { "CH13_Open:58", "Let's go." },
            { "CH13_Open:59", "[게이트>=0]…I think I can run today." },
            { "CH13_Open:60", "[게이트<0]…My legs aren't ready. One more week." },
            // CH13_Close
            { "CH13_Close:1", "'Were you scared?' 'Yeah.' 'Me too.'" },
            // CH14_Open
            { "CH14_Open:1", "She stands in the middle of the road at the bus stop. From here to the tower is 4.2. Today she can't make it from here." },
            { "CH14_Open:2", "He stands in that spot, at that angle, from eight years ago. She runs over and he turns his head — he was looking for the bus." },
            { "CH14_Open:3", "Not knocking them down?" },
            { "CH14_Open:4", "Not yet." },
            { "CH14_Open:5", "[게이트>=0]…I think I can run today." },
            { "CH14_Open:6", "[게이트<0]…My legs aren't ready. One more week." },
            // CH14_Close
            { "CH14_Close:1", "The two cartons of milk from that day." },
            // CH15_Open
            { "CH15_Open:1", "Haneul stands in the middle of the road at the bus stop. That angle. The tower." },
            { "CH15_Open:4", "The bus stop. The black sedan. The thin man checks his watch." },
            { "CH15_Open:5", "You have five minutes." },
            { "CH15_Open:6", "The two of them. She's hugging the board." },
            { "CH15_Open:7", "Ride well." },
            { "CH15_Open:8", "Okay." },
            { "CH15_Open:9", "Not 'okay'." },
            { "CH15_Open:10", "What." },
            { "CH15_Open:11", "Twenty. On your birthday. I'll be waiting under the tower." },
            { "CH15_Open:12", "That's eight years away." },
            { "CH15_Open:13", "I'm good at waiting." },
            { "CH15_Open:14", "You said waiting is the hardest thing." },
            { "CH15_Open:15", "That's why I'm good at it." },
            { "CH15_Open:16", "A heart sticker pressed into her hand. Two cartons of milk. He opens only one." },
            { "CH15_Open:17", "Drink the other one tomorrow." },
            { "CH15_Open:19", "The car pulls away. She jumps on the board and chases. A palm on the rear window." },
            { "CH15_Open:20", "I won't be late! Hey! I won't be late!" },
            { "CH15_Open:21", "(mouthing) I know." },
            { "CH15_Open:23", "The board catches a stone. She falls. The car turns the corner. She gets up and watches." },
            { "CH15_Open:25", "Her room. The calendar. The first time she writes it: 'Twentieth birthday — under the tower — Doyun.'" },
            { "CH15_Open:26", "— Seven years later —" },
            { "CH15_Open:27", "On the bus. Mom in a mask. By the window. Nineteen sees her off." },
            { "CH15_Open:28", "Don't go diving." },
            { "CH15_Open:29", "I won't." },
            { "CH15_Open:30", "I can't come for your birthday this year." },
            { "CH15_Open:31", "Come next year. I'll be twenty." },
            { "CH15_Open:32", "All right." },
            { "CH15_Open:33", "Next day. The smaller of two diving suits. Into the sea." },
            { "CH15_Open:35", "Birthday morning. A rough sea after the typhoon. She goes in alone with Dad's buoy. Underwater. Wavering sunlight. Black." },
            { "CH15_Open:38", "She opens her eyes. She's wearing the diving suit. The cliff steps. The kid spreads his arms and blocks the way." },
            { "CH15_Open:39", "Move." },
            { "CH15_Open:40", "Don't go." },
            { "CH15_Open:41", "I have to go down there." },
            { "CH15_Open:42", "Don't go!" },
            { "CH15_Open:43", "Not today." },
            { "CH15_Open:44", "Then when." },
            { "CH15_Open:45", "(He doesn't answer.)" },
            { "CH15_Open:46", "[게이트>=0]…I think I can run today." },
            { "CH15_Open:47", "[게이트<0]…My legs aren't ready. One more week." },
            // CH15_Close
            { "CH15_Close:1", "The memory stops here. From chapter 16 nothing comes back." },
            // CH16_Open
            { "CH16_Open:1", "A pale young man at the bus stop. She knows him not by his face but by the way he stands." },
            { "CH16_Open:2", "Shoulder brushes shoulder as he passes. The villagers greet only him." },
            { "CH16_Open:3", "I know him." },
            { "CH16_Open:4", "How?" },
            { "CH16_Open:5", "Dunno." },
            { "CH16_Open:6", "[게이트>=0]…I think I can run today." },
            { "CH16_Open:7", "[게이트<0]…My legs aren't ready. One more week." },
            // CH16_Close
            { "CH16_Close:1", "No cutscene. No memory." },
            // CH17_Open
            { "CH17_Open:1", "Through the dawn window, a handful of pills. The hospital bracelet on his wrist has never come off." },
            { "CH17_Open:2", "They say his heart stopped twice in Seoul." },
            { "CH17_Open:3", "Came down without the surgery." },
            { "CH17_Open:4", "Why." },
            { "CH17_Open:5", "Dunno." },
            { "CH17_Open:6", "Chasing Doyun she falls and scrapes her knee. No one passing looks. Only the kid comes and sits beside her." },
            { "CH17_Open:7", "I guess no one can see me." },
            { "CH17_Open:8", "I can see you." },
            { "CH17_Open:9", "[게이트>=0]…I think I can run today." },
            { "CH17_Open:10", "[게이트<0]…My legs aren't ready. One more week." },
            // CH17_Close
            { "CH17_Close:1", "She waves her arms in the middle of the road. He walks right through." },
            // CH18_Open
            { "CH18_Open:1", "He takes a letter from Haneul's mailbox and opens it. In a whole year she couldn't open one." },
            { "CH18_Open:2", "The empty school. Two of them looking at the same window. Only one reflection in the glass." },
            { "CH18_Open:3", "[게이트>=0]…I think I can run today." },
            { "CH18_Open:4", "[게이트<0]…My legs aren't ready. One more week." },
            // CH18_Close
            { "CH18_Close:1", "Only one reflection in the glass." },
            // CH19_Open
            { "CH19_Open:1", "The day before her birthday. Dad's anniversary. A letter from Mom, the first in a year." },
            { "CH19_Open:2", "I'll come tomorrow." },
            { "CH19_Open:3", "They walk the 4.2 km side by side in the rain. He doesn't know. Under the tower, two bunches of chrysanthemums. There's only one father. The card has run: only 'Ha…' remains." },
            { "CH19_Open:4", "As he stands, the hospital bracelet falls. Haneul picks it up — it's solid in her hand." },
            { "CH19_Open:5", "It's tomorrow, right." },
            { "CH19_Open:6", "How do you know?" },
            { "CH19_Open:7", "Just do." },
            { "CH19_Open:8", "That night. She hangs the bracelet on the calendar nail. Beside the 'Doyun' copied over for eight years, she writes in pencil: 'Haneul.'" },
            { "CH19_Open:9", "[게이트>=0]…I think I can run today." },
            { "CH19_Open:10", "[게이트<0]…My legs aren't ready. One more week." },
            // CH19_Close
            { "CH19_Close:1", "So you're already gone. How will you come tomorrow." },
            { "CH19_Close:2", "On the night she decides the dead can't come, she puts her own name beside the promise." },
            // CH20_Open
            { "CH20_Open:1", "Her twentieth birthday. Morning. Nothing of hers is left in the house. The porch is empty too." },
            { "CH20_Open:2", "All that's left: the calendar and eight heart stones on the shelf. She takes the bracelet off the calendar and puts it on." },
            { "CH20_Open:3", "A typhoon. The same bus stop, the same 'Service suspended.' A new heart buoy in the stone wall, paint still wet on her hand. Bada is nowhere today." },
            { "CH20_Open:4", "The last 4.2 km. No kid. When she falls, no hand comes. For the first time she has to get up alone." },
            { "CH20_Open:5", "[게이트>=0]…I think I can run today." },
            { "CH20_Open:6", "[게이트<0]…My legs aren't ready. One more week." },
            // CH20_Close
            { "CH20_Close:1", "She arrives with half the sunset left." },
            // END_A
            { "END_A:1", "Half the sunset left. Under the tower, Mom kneels and lays chrysanthemums, beside the two bunches Doyun left yesterday." },
            { "END_A:2", "A little way off, Doyun sits. His back. One hand on his chest. Waiting for her to leave." },
            { "END_A:3", "Mom." },
            { "END_A:4", "(She can't hear.)" },
            { "END_A:5", "Getting up, Mom sees him. Stops. Looks a long time. The boy who hauled her through the rain eight years ago. Doyun stands." },
            { "END_A:6", "You've grown." },
            { "END_A:7", "Yes." },
            { "END_A:8", "Our Haneul was waiting for you." },
            { "END_A:9", "(He can't answer.)" },
            { "END_A:10", "Thank you. For back then." },
            { "END_A:11", "No. Don't." },
            { "END_A:12", "Haneul stands between them. She raises a hand. Neither looks." },
            { "END_A:13", "Mom. I'm right here." },
            { "END_A:14", "Mom walks down. Haneul starts to follow, then stops. Looks at the tower. The sunset shrinks. She turns." },
            { "END_A:15", "Doyun." },
            { "END_A:16", "He turns. His face lights up. Color returns: her face first, then his, the gold silvergrass, the sunset, the sea. The tower's hum turns clear." },
            { "END_A:17", "Haneul." },
            { "END_A:18", "Why are you so late." },
            { "END_A:19", "Where'd you learn to talk like that." },
            { "END_A:20", "Eight years." },
            { "END_A:22", "Haneul laughs out loud. The first time in twenty chapters." },
            { "END_A:23", "Hands. The bracelet. The card: 'Haneul.' Chrysanthemums. Looking at her, he picks up the card and hands it over. She nods." },
            { "END_A:25", "The kid. He doesn't knock the stones down. He adds one. Four." },
            { "END_A:27", "Why add one." },
            { "END_A:28", "Because I have to go out again." },
            { "END_A:29", "When will you be back." },
            { "END_A:30", "Next year." },
            { "END_A:31", "(He smiles. The silvergrass closes. No raincoat.)" },
            { "END_A:33", "— Spring —" },
            { "END_A:34", "The coast road, the canola truly yellow. He walks. Board wheels beside him. The board rolls by, its rider out of frame. He looks over and smiles. Behind, the two suits walk instead of running." },
            { "END_A:36", "The store. A hand holding two cartons of milk. The door. The bell, twice." },
            { "END_A:37", "Two again today?" },
            { "END_A:38", "Yes. Two." },
            { "END_A:39", "The bus stop. 'Service resumed.' The bus stops. The door opens. He steps back half a pace and holds out his hand." },
            { "END_A:40", "You first." },
            { "END_A:42", "He taps the card. Beep. A beat. Beep. The driver checks the mirror." },
            { "END_A:43", "Just you?" },
            { "END_A:44", "(He smiles.)" },
            { "END_A:45", "No." },
            { "END_A:47", "He leaves the window seat empty and sits on the aisle. The board on his knees. Two milks. He opens one. Click. Touches his chest once. Smiles." },
            { "END_A:48", "What the window reflects is never shown. Black. A second click." },
            // END_B
            { "END_B:1", "Half the sunset left. Under the tower, Mom kneels and lays chrysanthemums, beside the two bunches Doyun left yesterday." },
            { "END_B:2", "A little way off, Doyun sits. His back. One hand on his chest. Waiting for her to leave." },
            { "END_B:3", "Mom." },
            { "END_B:4", "(She can't hear.)" },
            { "END_B:5", "Getting up, Mom sees him. Stops. Looks a long time. The boy who hauled her through the rain eight years ago. Doyun stands." },
            { "END_B:6", "You've grown." },
            { "END_B:7", "Yes." },
            { "END_B:8", "Our Haneul was waiting for you." },
            { "END_B:9", "(He can't answer.)" },
            { "END_B:10", "Thank you. For back then." },
            { "END_B:11", "No. Don't." },
            { "END_B:12", "Haneul stands between them. She raises a hand. Neither looks." },
            { "END_B:13", "Mom. I'm right here." },
            { "END_B:14", "Mom walks down. Haneul starts to follow, then stops. Looks at the tower. The sunset shrinks. She turns." },
            { "END_B:15", "Doyun." },
            { "END_B:16", "He rises. Slowly. Turns. His eyes miss hers by a hand's width." },
            { "END_B:17", "Are you there?" },
            { "END_B:18", "(She holds her breath.)" },
            { "END_B:19", "I think you are." },
            { "END_B:20", "A hand groping the air. Haneul looks at it. Stops. Takes it." },
            { "END_B:22", "He breathes in sharply. Between their hands, a heart lights up. The only color on screen." },
            { "END_B:23", "You're here." },
            { "END_B:24", "Can you see me?" },
            { "END_B:25", "No." },
            { "END_B:26", "But I can hold you." },
            { "END_B:27", "Haneul slips the bracelet off her wrist and onto his. He touches it." },
            { "END_B:28", "This—" },
            { "END_B:29", "(No answer.)" },
            { "END_B:30", "The card by the flowers. The side that didn't run: 'Haneul.' Two bunches. Yesterday and today. Behind them a framed photo: a black ribbon. Her own face." },
            { "END_B:31", "So it wasn't you who died?" },
            { "END_B:32", "(He can't hear.)" },
            { "END_B:34", "The last piece: underwater, a hand gripping the buoy, the bubbles stopping." },
            { "END_B:36", "Haneul calls down the hill. An orange raincoat rises out of the silvergrass. He looks where she's looking." },
            { "END_B:37", "Bada!" },
            { "END_B:38", "Who?" },
            { "END_B:39", "He's been with me all year." },
            { "END_B:40", "There's no one there." },
            { "END_B:41", "The kid looks only at Haneul." },
            { "END_B:42", "I have to go now." },
            { "END_B:43", "Where." },
            { "END_B:44", "Hey. How many times did you pick me up?" },
            { "END_B:45", "Dunno." },
            { "END_B:46", "Me neither." },
            { "END_B:47", "Lots." },
            { "END_B:48", "He walks to the stone wall. Sweeps the three stones down with his hand. One by one they fall." },
            { "END_B:49", "Why'd you knock them down." },
            { "END_B:50", "Because I came back." },
            { "END_B:51", "A heart stone from his pocket. Into her hand. The ninth." },
            { "END_B:52", "Dad?" },
            { "END_B:53", "(He looks back. Says nothing.)" },
            { "END_B:54", "It's you, isn't it." },
            { "END_B:55", "(He smiles.)" },
            { "END_B:57", "Not a child's voice. Low, thick, a voice she knows." },
            { "END_B:58", "Just one more catch and we're fine." },
            { "END_B:60", "The silvergrass closes. No raincoat. No torn sleeve. Below the cliff a red buoy surfaces, turns once under the tower light, and is gone." },
            { "END_B:61", "Thank you." },
            { "END_B:63", "He walks down the hill. His right arm stretches out of frame. Held." },
            { "END_B:65", "Next morning. The store. The bell." },
            { "END_B:66", "Two again today?" },
            { "END_B:67", "Yes. Two." },
            { "END_B:69", "The door closes. The bell rings once more. No one went out." },
        };
    }
}
