// <auto-generated> Tools/Story/cutscene_txt.py import — 편집용 txt에서 생성. 직접 편집하지 말 것.
using System.Collections.Generic;

namespace CoastRun
{
    public static partial class ChapterScript
    {
        public static readonly Dictionary<int, string> Titles = new Dictionary<int, string>
        {
            { 1, "1장" },
            { 2, "2장" },
            { 3, "3장" },
            { 4, "4장" },
            { 5, "5장" },
            { 6, "6장" },
            { 7, "7장" },
            { 8, "8장" },
            { 9, "9장" },
            { 10, "10장" },
            { 11, "11장" },
            { 12, "12장" },
            { 13, "13장" },
            { 14, "14장" },
            { 15, "15장" },
            { 16, "16장" },
            { 17, "17장" },
            { 18, "18장" },
            { 19, "19장" },
            { 20, "20장" },
        };

        public static readonly Dictionary<string, VnLine[]> Scenes = new Dictionary<string, VnLine[]>
        {
            { "PRO", new[]
            {
                new VnLine("BG", "HanulRoom", "", "", ""),
                new VnLine("NARR", "", "(프롤로그 — 새 대본 자리)", "", ""),
            } },
            { "CH01_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(1장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH01_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(1장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH02_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(2장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH02_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(2장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH03_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(3장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH03_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(3장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH04_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(4장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH04_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(4장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH05_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(5장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH05_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(5장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH06_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(6장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH06_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(6장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH07_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(7장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH07_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(7장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH08_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(8장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH08_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(8장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH09_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(9장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH09_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(9장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH10_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(10장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH10_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(10장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH11_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(11장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH11_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(11장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH12_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(12장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH12_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(12장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH13_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(13장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH13_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(13장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH14_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(14장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH14_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(14장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH15_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(15장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH15_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(15장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH16_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(16장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH16_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(16장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH17_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(17장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH17_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(17장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH18_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(18장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH18_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(18장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH19_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(19장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH19_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(19장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "CH20_Open", new[]
            {
                new VnLine("BG", "TowerDay", "", "", ""),
                new VnLine("NARR", "", "(20장 오프닝 — 새 대본 자리. 챕터 마지막 주에 이벤트로 재생된다.)", "", ""),
                new VnLine("NARR", "", "[게이트>=0]…달릴 수 있을 것 같다.", "", ""),
                new VnLine("NARR", "", "[게이트<0]…아직은 다리가 못 버틴다. 이번 주는 더 키우자.", "", ""),
            } },
            { "CH20_Close", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(20장 클로즈 — 새 대본 자리. 송전탑 도착 후 재생.)", "", ""),
            } },
            { "END_A", new[]
            {
                new VnLine("BG", "TowerSunset", "", "", ""),
                new VnLine("NARR", "", "(엔딩 A — 새 대본 자리)", "", ""),
            } },
            { "END_B", new[]
            {
                new VnLine("BG", "TowerNight", "", "", ""),
                new VnLine("NARR", "", "(엔딩 B — 새 대본 자리)", "", ""),
            } },
        };
    }
}
